### ISSUE TITLE
Custom Incident name in Dispatch

### ISSUE THREAD

**Issue by vikassinha2019** [Netflix/dispatch#2059]
We are currently creating tickets in Jira for our alerts, and they have the naming convention as ABC-12345 (12345 number is as per the ticket counter in Jira). 
Now creating the ticket within Dispatch will have its own sequence number for the ticket ID (e.g. dispatch-default-default-101).  So, how we can use the Jira ticket incident number to create dispatch incident id as dispatch-defaul-default-12345. 

I know we can play around the following line to modify incident ID

https://github.com/Netflix/dispatch/blob/b31bf522886c1d458190b3d0228fc3c2a7d12f2a/src/dispatch/plugins/dispatch_core/plugin.py#L157

However, do we have an easy option to utilise a parameter passed to Dispatch API, so that it creates incident with the corresponding ID? Or how can we play around with {incident.id} to fulfil the mentioned scenario.

Because having a same ID across platform will help in ticket correlation area.

**Comment by kevgliss** [comment]
If you enable the Jira dispatch plugin, dispatch will use whatever is returned from Jira. In this case, it would cleanly use the next available Jira ticket number as the dispatch ticket ID. If you want to backport your existing Jira into Dispatch, you can but would have to script something up, we don't have something generic because Jira projects use unique identifiers.
