### ISSUE TITLE
Roadmap for Dispatch

### ISSUE THREAD

**Issue by darrenhaken** [Netflix/dispatch#271]
Hi there,

First of all, I am really thrilled you've open-sourced this project. 
It looks exactly like the sort of thing we've been looking for to improve our approach to incident management.

To this end, I was wondering if you had a roadmap for features you'll be adding?
I was also keen to add some further integrations but I wanted to check you're happy to receive support and contributions?

**Comment by kevgliss** [comment]
Hi, @darrenhaken first off we're definitely open to contributions in whatever capacity. As far as roadmaps go, we've got our own internal roadmap but nothing public at this point. 

In very general terms I would say our near-term road map has the following themes:

**Maturity for OSS** 
- Decoupling plugins and allowing them to be a value add instead of a requirement to use Dispatch at all. See #55 
- Allowing dispatch to be easier to configure and setup from the Admin UI

**Deeper Insights on incident data**
- Surfacing incident data to stakeholders. We are collecting a large amount of structured incident data we're not currently making use of. We will be trying to leverage that data and exposing it to folks who are interested in the form of metrics (graphs, stats) and timelines.

As far as additional plugins go we're currently happy with the plugins we currently have for our use internally. So we won't be developing more plugins internally but are of course open contributions of others.
