### ISSUE TITLE
postgres role doesnt exist

### ISSUE THREAD

**Issue by manireddyk** [Netflix/dispatch#2766]
I have noticed in the new release, after the dispatch-build , when its asking to load sample data, I have give yes, there I could see this role error, does it effect anything
<img width="463" alt="image" src="https://user-images.githubusercontent.com/46611593/207322310-051a11f1-b701-4def-ae95-b18158e17dac.png">

& in the older release while initializing db, I saw this error
dispatch-20220801- alembic.util.exc.CommandError: Can't locate revision identified by 'eb348d46afd0'

**Comment by mvilanova** [comment]
If the role `postgres` in the database doesn't exist, you'll need to manually create it to unblock yourself. We can add that step to the `install.sh` [script](https://github.com/Netflix/dispatch-docker/blob/master/install.sh) in the future.

**Comment by vindex10** [comment]
For me it happend because in the .env.example the default user if "dispatch", while dump is made on behalf of "postgres". I just replaced all mentions of "OWNER TO postgres" with "OWNER TO dispatch" in the downloaded dump: dispatch-sample-data.dump

the error was gone, do you think it could be a solution for the install.sh as well? to replace owner with the user mentioned in the config on the fly?
