### ISSUE TITLE
Use of Google admin SDK

### ISSUE THREAD

**Issue by varunachar** [Netflix/dispatch#384]
We are doing a PoC for dispatch and would like to understand the need for using the Google Admin SDK? Wasn't clear from the documentation. The admin sdk has a lot of privileges and hence raising alarms internally.

**Comment by kevgliss** [comment]
As part of the incident creation process, we create several different resources to help us manage the incident. 

By default, this includes creating Google Docs for the incident collaboration a Google Team Drive for artifact management, a Google Meet for video conferencing, and a Google Group to manage permissions and notifications to the aforementioned Google resources.

You specifically mentioned the Admin SDK, unfortunately, in order to be able to create and manage Google Groups, this permission is required (which we aren't particularly fond of either). 

We've been working toward making the creation of these resources _optional_  (See: #55)  but they are currently required by Dispatch.
