### ISSUE TITLE
Lifecycle of an incident managed within Slack actions

### ISSUE THREAD

**Issue by batisteo** [Netflix/dispatch#460]
**Is your feature request related to a problem? Please describe.**
We are evaluating Dispatch to replace our in-house solution based on a Slack bot.

**Describe the solution you'd like**
I wonder if it would be possible to control the workflow/lifecycle of an incident directly in Slack with buttons.  
I’m not sure how is it done right now, and I would be curious to see if you would be interested in us adding this functionality to the Slack plugin.

_cc @aexvir_

**Comment by kevgliss** [comment]
Hi @batisteo, Dispatch does allow you to manage the entire lifecycle of an incident from Slack using a combination of buttons, modals, dialogs, and commands. 

This includes things like:

- Assigning incident roles
- Updating incident information (status, description, type, etc.,)
- Creating status reports
- Listing incident resources
- Creating a new incident
- Many more

There are a few features that are only enabled via the Admin UI mostly because of limitations of the Slack Block Kit UI (things that require typeahead's like tagging). 

Additionally, we would be open to contributions to this space.
