### ISSUE TITLE
Signal can not create case automatically 

### ISSUE THREAD

**Issue by tiankai0114** [Netflix/dispatch#5145]
Hi Everyone,

I added signal definition and checkbox create case, however when I use api to create a single instance, response is 200 ok, however only create a signal on Dispatch, did not create case, did everyone knows what happened?  from web logs, shows only create signal api, did not have trigger any api about case
![WechatIMG1353](https://github.com/user-attachments/assets/ffcf3d1f-b683-4558-9873-c78de960b861)
![WechatIMG1354](https://github.com/user-attachments/assets/65ecad72-fc6a-4053-ace9-0f2693e52e2d)

http://localhost:8000/api/v1/default/signals/instances

{
    "project": {
        "name" : "default"
    },
    "raw" : {
        "name" : "UAT1 down",
        "security" : "high",
        "owner" : "test@123.com",
        "description": "UAT1 down, please take a look"
    }
}

**Comment by andrewboxonko** [comment]
@wssheldon i saw this pr https://github.com/Netflix/dispatch/pull/4982 where you did some changes to that

I suppose main_processing_loop should iterate through signals and process them, but I did not find any usage of that function. or maybe it's supposed to work other way

Anyway, I have the same problems. Cases are not created when signal instance is created

**Comment by wssheldon** [comment]
Hello, @andrewboxonko and @tiankai0114 

You may need to enable the signal processor, which you can do via the CLI:

`dispatch signals process`

This command will continuously read signal instances (that have no associated case or filter action) from the database and send them through the `signal_instance_create_flow` function.

Without any output from either this process or the web server it will be hard to know why the case is not being created as it could be for many different reasons.

**Comment by tiankai0114** [comment]
Hi. @wssheldon ,

I execute command **dispatch signals process** in docker, it can create case depends on signal, however, I need to manually enter docker and execute this command to start the work. Do you know how to keep this automatic running? Is it related to scheduler, thanks.

**Comment by wssheldon** [comment]
Glad to hear you got the case creation going. `dispatch signals process` will continue to run after you execute it, just like the web server itself. You should run this command in your production deployment to enable signal processing. You may want to run `dispatch signals process` on a separate container or instance.

**Comment by wssheldon** [comment]
Your JSON payload likely does not match a signal definition and is getting dropped. Make sure the external id/variant match a defined signal instance.

**Comment by andrewboxonko** [comment]
@wssheldon just checked, they are matching, but still the same result

<img width="1194" alt="image" src="https://github.com/user-attachments/assets/5fefe85b-3b0f-410e-9ea0-1ad55be26b83">
<img width="1199" alt="image" src="https://github.com/user-attachments/assets/21be6814-ba7a-4e7b-8e70-09d0fee2c1ac">

**Comment by wssheldon** [comment]
Try adding a variant for good measure

**Comment by andrewboxonko** [comment]
@wssheldon Thanks, I was able to create a case after signal processing. But I have an additional question and It would be awesome if you could help since I did not find much in the docs, unfortunately. I am interested in using custom data for incident/case. I saw you have entities which can be used for that purpose, I was able to get created entities from my signal based on the JSON path. I would like to know if there is the possibility of assigning an entity to a case/incident. Ideally, I would like to create an incident with custom data directly. Maybe the is a way to do that or you can advise another way if that's possible. Thanks!

**Comment by wssheldon** [comment]
Entities are currently only associated with Signal Instances. I would be interested in understanding more about your use case, re:

>  I am interested in using custom data for incident/case

Could you provide a practical example of what you'd like to do, your specific domain, and what the inputs/outputs are?

**Comment by andrewboxonko** [comment]
@wssheldon We are currently in the initial stage and aiming to create basic incidents. We plan to develop our UI based on the dispatch API. Our use case scenario involves creating incidents based on real issues that could occur in the physical place/building/store. So for that reason, we would like to add information about where exactly the problem happened. That's why I am interested in having custom data. By custom data, I meant the possibility of creating incidents and having some custom attributes linked to them, such as an address, building/store name and so on. In the future, we also would like to use signals, but for now, we need to finalize the first stage

**Comment by andrewboxonko** [comment]
@wssheldon what do you think is it possible to achieve?

**Comment by wssheldon** [comment]
@andrewboxonko You should be able to leverage the `Tag` construct, to build up a corpus on tags that are relevant to you, and tag your incidents with those tags.

**Comment by andrewboxonko** [comment]
@wssheldon, yeah, the usage of tags looks fine. Thanks a lot. Also, I have an additional question regarding logs. Is it possible to store the changes that could be made to an incident in dispatch? For example, would you like to store and get the data (log) about changes made to an incident (edit of name, reporter and so on)? Would it be possible to achieve this using dispatch?

**Comment by andrewboxonko** [comment]
@wssheldon could we somehow use custom events for that purpose?

**Comment by OLeh125** [comment]
@wssheldon I'm also interested in custom events. Is there a way to add them somehow?
