### ISSUE TITLE
Netflix Dispatch Authentication using SAML SSO.

### ISSUE THREAD

**Issue by mccannm1** [Netflix/dispatch#537]
Hello  @kevgliss @mvilanova 

May I ask a short question please?  How does login to Netflix Dispatch work on a high level? How may I add users?
Specifically if I want to use SAML Authentication to login corporate users to Dispatch who would be using it as a 
solution for incident management, is it possible to point Netflix Dispatch to a corporate Identity provider IdP for login
using SAML?

 authentication is presently disabled 
DISPATCH_AUTHENTICATION_PROVIDER_SLUG= 

Can this parameter be used to point to a SAML IdP (for SSO login?

DISPATCH_AUTHENTICATION_PROVIDER_SLUG ['default': dispatch-auth-provider-basic]
Used by Dispatch to determine which authentication provider to use, by default Dispatch ships with a PKCE authentication provider.

Thats all Thanks

**Comment by kevgliss** [comment]
We don't currently support SAML as an authentication provider (we _do_ support PKCE). In order to add regular SAML you would need to add a new `AuthenticationProviderPlugin`, e.g:

https://github.com/Netflix/dispatch/blob/develop/src/dispatch/plugins/dispatch_core/plugin.py#L66

We don't currently have a timeframe to add that functionality ourselves but would be more than willing to merge in PRs with that support.

**Comment by mccannm1** [comment]
Thank you @kevgliss
