### ISSUE TITLE
Pagerduty plugin works only if your escalation policy has a schedule.

### ISSUE THREAD

**Issue by gargrag** [Netflix/dispatch#541]
**Describe the bug**
The Pagerduty plugin expects your escalation policy to be tied to a schedule, while there are other options.
**To Reproduce**
1. configure the escalation policy associated with the Pagerduty service integrated with dispatch, to directly notify a person instead of a schedule.
2. Try creating a new incident

**Expected behavior**
Please let me know if this is the expected behavior so we can improve the documentation to specify this requirement, Otherwise, the plugin needs a patch here: https://github.com/Netflix/dispatch/blob/37ebf763e6c24bf8a0739e99ddd1000a72685a2b/src/dispatch/plugins/dispatch_pagerduty/service.py#L17-L20
***Screenshots***
![image](https://user-images.githubusercontent.com/967311/91913483-9775f500-ec6a-11ea-8015-2311bae0b9ff.png)

**Comment by mvilanova** [comment]
Hi @gargrag, that's correct. The current implementation expects a schedule to be associated with the escalation policy, because that's how we use it internally, but it's not the only option like you said. We'll try to carve time to work on a patch, or if you want to cut a PR for it, we will be happy to review it.

We should also migrate to https://github.com/PagerDuty/pdpyras in the near future, as https://github.com/PagerDuty/pagerduty-api-python-client has been deprecated.

**Comment by mvilanova** [comment]
@gargrag good to close here?
