### ISSUE TITLE
Advice for adding new features

### ISSUE THREAD

**Issue by lhole** [Netflix/dispatch#65]
Hi there,

Our team is currently reviewing incident command tools to replace our in house built one. We'd like to empower teams throughout our organisation to create and run incidents themselves. I was hoping that you could help me understand what would be involved in us adding the following features, and whether we could use the current plugin system for it?

1. Our organisation uses slack heavily - we'd like to be able to create incidents within slack rather than a separate UI
2. We need a tool that's easy for infrequent users to use - we'd like to use slack UIs and buttons rather than slash commands for initiating most of the interactions
3. We use Zoom for our calls - we'd like to create a single official zoom meeting for every incident
4. Our organisation spans multiple timezones and it can get confusing if we're not explicit - we'd like to use a hard-coded timezone everywhere it's mentioned in the UI or allow for entering in local time and convert to a hard-coded timezone
5. Some of our incidents are ongoing for a while before they're reported - we'd like to separate the start time and reported time for incidents.

Thanks a lot,

Laurence

**Comment by kevgliss** [comment]
Hi @lhole ,

When we originally set out to develop Dispatch, our core thesis was that every incident has the potential to be a participant's first incident. With that in mind, we've tried to build a tool that has the lowest learning curve we could manage (using existing collaboration tools, orienting new users with links, and helpful descriptions, etc.,).

To your specific points:

>  Our organization uses slack heavily - we'd like to be able to create incidents within slack rather than a separate UI

We too would like this feature (and have it in our backlog). We focused on a UI form as we could control the feedback given to the user. If you would be interested in adding it yourself, all the pieces are already there just not put together. Take a look at how we do the `edit-incident` dialog for inspiration:

https://github.com/Netflix/dispatch/blob/develop/src/dispatch/plugins/dispatch_slack/views.py#L316

> We need a tool that's easy for infrequent users to use - we'd like to use slack UIs and buttons rather than slash commands for initiating most of the interactions. 

I think we're generally aligned here as well, we've chosen slash commands because, at the time, they were able to give us the functionality we needed. That being said as slack functionality evolves (with more hooks). I would expect us to use and implement those features aggressively. 

> We use Zoom for our calls - we'd like to create a single official zoom meeting for every incident

We would also like this feature (Hangouts for our use case), there is already a `conference` plugin type. At one point I did have a PR that would add this functionality, but it was never fully merged. Regardless, in the Zoom case, you would be responsible for creating a Zoom plugin to manage creation.

See: https://github.com/Netflix/dispatch/blob/develop/src/dispatch/plugins/bases/conference.py

> Our organization spans multiple timezones and it can get confusing if we're not explicit - we'd like to use a hard-coded timezone everywhere it's mentioned in the UI or allow for entering in local time and convert to a hard-coded timezone

Internally dispatch normalizes all timestamps to UTC, I don't believe these are localized anywhere in the UI. 

> Some of our incidents are ongoing for a while before they're reported - we'd like to separate the start time and reported time for incidents.

We also have this issue. Today, a Dispatch incident has a few distinct times:
- created _at (the time when the record of the incident created in Dispatch itself)
- updated_at (the time when the record was last updated in Dispatch itself)
- reported_at (either the same as created_at or specified in the Admin UI)
- stable_at (the time when the incident was marked stable or specified in the Admin UI)
- closed_at (the time when the incident was marked closed or specified in the Admin UI)

To be frank, I do think that Dispatch can fit your use case but, as an opensource project, it probably won't be as turn-key as other vendor products. That said we've found that it to be extremely flexible and has allowed us to deeply integrated it into our organization.

Cheers,
Kevin

**Comment by mvilanova** [comment]
Hi @lhole,

> Our organisation uses slack heavily - we'd like to be able to create incidents within slack rather than a separate UI

Here are the steps if you decide to add the `/dispatch-report-incident` command:

- Define the command in the Slack config [here](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/plugins/dispatch_slack/config.py) and import it where needed
- Add a function that creates the reporting dialog. There are several in the `views.py` module.
- Map the command to the function [here]. (https://github.com/Netflix/dispatch/blob/develop/src/dispatch/plugins/dispatch_slack/views.py#L496)
- Finally, map the command to the flow you want to run when the user submits the form. In this case, you should call the [incident.service.create()](https://github.com/Netflix/dispatch/blob/develop/src/dispatch/incident/service.py#L115) function.

> We need a tool that's easy for infrequent users to use - we'd like to use slack UIs and buttons rather than slash commands for initiating most of the interactions

Can you elaborate a little bit more about the UIs and buttons you had in mind? Before we decided to go with slash commands we looked at [Actions](https://api.slack.com/interactivity/actions). Unfortunately, they are hard to find and Slack only allows you to add 5 per App. You can add as many slash commands as you want AFAIK. We also played with [Workflow Builder](https://slackhq.com/automate-tasks-in-slack-with-workflow-builder). The form looked really nice, but Slack didn't support sending the responses to an API endpoint, only to a channel or via DM.
